Short cmake introduction
========================

cmake has to be called with the path to the source-dir as a parameter.
e.g.:

     cmake /home/foobar/source/wormux

This makes it possible to have source and build directories seperated.
For example, you can build in /tmp/wormux-build and leave the source-dir untouched,
which makes it easier to remove all files generated by the build-system.

After running cmake (which just generates the Makefiles for the native make-system)
you have to call make from the build-dir (which can be the source-dir) in order
to get Wormux compiled:

     make

To install Wormux just call

     make install

This command install everything needed to run wormux in $CMAKE_INSTALL_PREFIX
which defaults to /usr/local (see below how to change that).


Further cmake options:
----------------------

To specify another install prefix, just pass the following as a parameter for cmake:
     -DCMAKE_INSTALL_PREFIX=/foo/bar
(this corresponds to --prefix=/foo/bar with autotools-configure)

To specify another build-type, pass the following parameter:
     -DCMAKE_BUILD_TYPE=XXXXX
where XXXXX is one of the following:
     None Debug Release RelWithDebInfo MinSizeRel

To get a more verbose compile output, call make like this:
     make VERBOSE=1

