static:
	make -f Makefile.static

dynamic:
	make -f Makefile.dynamic

help:
	@echo "* Use 'make' to build a statically linked binary (default)"
	@echo "* Use 'make dynamic' to build a dynamic binary"

clean:
	@rm -f *.o *~ wormux_server 2>&1 > /dev/null
