CXX=g++
CXXFLAGS:=-g -DDEBUG -Wall -Werror $(CXXFLAGS)

OBJ=main.o config.o server.o client.o net_data.o download.o sync_slave.o clock.o stat.o

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -MMD -I../common/ -c -o $@ $<

wormux_server: $(OBJ)
	$(CXX) $(CXXFLAGS) -o wormux_server $(OBJ) ../common/wormux_server_common.a $(LDFLAGS)

-include $(OBJ:.o=.d)
