
SET(DATA_FILES
object/star.png
object/smoke3.png
object/bonus_box.png
object/smoke.png
object/fire.png
object/barrel.png
object/ill_bubble.png
object/dark_smoke.png
object/smoke2.png
object/pink_star.png
object/yellow_star.png
object/blue_star.png
object/medkit.png
wormux_128x128.png
music/ingame/ingame.m3u
music/profile.xml
music/menu/Olivier_Militon.-.Le_Calumet.ogg
music/menu/menu.m3u
music/menu/Olivier_Militon.-.Le_Calumet_F.ogg
interface/small_background_interface.png
interface/background_interface.png
interface/button4.png
interface/button1.png
interface/clock.png
interface/button3.png
interface/wind_indicator.png
interface/clock_background.png
interface/button2.png
interface/quit.png
interface/wind.png
interface/cursors/hand-fire.left.png
interface/cursors/arrow-left.png
interface/cursors/arrow-down.left.png
interface/cursors/arrow-top.left.png
interface/cursors/arrow-down.png
interface/cursors/arrow-down.right.png
interface/cursors/hand-cursor.png
interface/cursors/hand-fire.right.png
interface/cursors/arrow-top.right.png
interface/cursors/arrow-right.png
interface/cursors/hand-fire.png
interface/cursors/hand-move.png
interface/cursors/arrow-top.png
interface/pause.png
interface/button5.png
weapons.dtd
gfx/pointer.png
gfx/arrow.png
gfx/water_bottom.png
gfx/water.png
wormux.desktop
graphism.xml
weapons.xml
map/desert/desert_preview.jpg
map/desert/desert.png
map/desert/config.xml
map/desert/desert_bg.jpg
map/halloween/confetis.png
map/halloween/noir_lune.jpg
map/halloween/config.xml
map/halloween/halloween.png
map/halloween/preview.jpg
map/leafs/front.png
map/leafs/birds.png
map/leafs/config.xml
map/leafs/back.jpg
map/leafs/preview.jpg
map/goodandevil/sky.jpg
map/goodandevil/config.xml
map/goodandevil/goodandevil.png
map/goodandevil/preview.jpg
map/easterisland/sky.jpg
map/easterisland/map.png
map/easterisland/config.xml
map/easterisland/wp.png
map/easterisland/preview.jpg
map/catacombes/config.xml
map/catacombes/background1.png
map/catacombes/sky1.jpg
map/catacombes/preview.jpg
map/map.dtd
map/aquarium/sky.jpg
map/aquarium/config.xml
map/aquarium/background.png
map/aquarium/preview.jpg
map/araignee/abeille.png
map/araignee/fond.jpg
map/araignee/araignee.png
map/araignee/config.xml
map/araignee/preview.jpg
map/electronik/sky.jpg
map/electronik/config.xml
map/electronik/background.png
map/electronik/preview.jpg
map/random/sky.jpg
map/random/texture.png
map/random/config.xml
map/random/palm-tree.png
map/random/tresor2.png
map/random/tresor1.png
map/random/preview.jpg
map/prehistorik/fond.jpg
map/prehistorik/config.xml
map/prehistorik/prehistorik.png
map/prehistorik/preview.jpg
map/space/space.png
map/space/config.xml
map/space/lune.jpg
map/space/preview.jpg
map/paradis/decor_paradis.png
map/paradis/paradis_preview.jpg
map/paradis/config.xml
map/paradis/decor_paradis_BG.jpg
map/vulcano/sky2.jpg
map/vulcano/config.xml
map/vulcano/background.png
map/vulcano/preview.jpg
map/champignon/sky.jpg
map/champignon/config.xml
map/champignon/background.png
map/champignon/preview.jpg
map/monkeybubbleworld/sky.jpg
map/monkeybubbleworld/monkeybubbleworld.png
map/monkeybubbleworld/config.xml
map/monkeybubbleworld/preview.jpg
map/monkeybubbleworld/feuille.png
map/cheese/sky.jpg
map/cheese/minicheese.png
map/cheese/config.xml
map/cheese/preview.jpg
map/cheese/emmental.png
map/hell/bones.png
map/hell/hellsky.jpg
map/hell/hell.png
map/hell/config.xml
map/hell/preview.jpg
map/cowland/cowland.png
map/cowland/nuage.png
map/cowland/config.xml
map/cowland/cowland_bg.jpg
map/cowland/preview.jpg
map/pirates/pirates.png
map/pirates/config.xml
map/pirates/islands.jpg
map/pirates/preview.jpg
map/grenouilles/jungle.jpg
map/grenouilles/nuage.png
map/grenouilles/config.xml
map/grenouilles/grenouilles.png
map/grenouilles/preview.jpg
map/battlenight/battlenight-bg.jpg
map/battlenight/config.xml
map/battlenight/battlenight-fg.png
map/battlenight/battlenight-all.jpg
map/noel/config.xml
map/noel/nege-anim.png
map/noel/bleu.jpg
map/noel/preview.jpg
map/noel/noel.png
map/banquise/banquise.png
map/banquise/background.jpg
map/banquise/flocon.png
map/banquise/config.xml
map/banquise/preview.jpg
map/island/sky.jpg
map/island/island.png
map/island/config.xml
map/island/preview.jpg
map/qingqong/sky.jpg
map/qingqong/config.xml
map/qingqong/preview.jpg
map/qingqong/qingqong.png
map/crystal/sky.jpg
map/crystal/config.xml
map/crystal/crystal.png
map/crystal/preview.jpg
map/wildwestdv/backgr.jpg
map/wildwestdv/wildwestdv.png
map/wildwestdv/config.xml
map/wildwestdv/preview.jpg
map/arbre/fond.jpg
map/arbre/arbre.png
map/arbre/config.xml
map/arbre/gland-anim.png
map/arbre/preview.jpg
map/greehills/star.png
map/greehills/greenhills_sky.jpg
map/greehills/config.xml
map/greehills/greenhills.png
map/greehills/preview.jpg
wormux_32x32.png
body/snortteam/c1.png
body/snortteam/jetpack-belt.png
body/snortteam/helmet.png
body/snortteam/black.png
body/snortteam/tail.png
body/snortteam/body.png
body/snortteam/jetpack.png
body/snortteam/config.xml
body/snortteam/head.png
body/snortteam/c2.png
body/snortteam/dead.png
body/snortteam/arm.png
body/snortteam/jetpack-fire.png
body/snortteam/yoyo.png
body/beastieteam/arm-right.png
body/beastieteam/c1.png
body/beastieteam/jetpack-heli.png
body/beastieteam/helmet.png
body/beastieteam/black.png
body/beastieteam/tail.png
body/beastieteam/body.png
body/beastieteam/jetpack.png
body/beastieteam/config.xml
body/beastieteam/head.png
body/beastieteam/c2.png
body/beastieteam/dead.png
body/beastieteam/arm-left.png
body/beastieteam/yoyo.png
body/beastieteam/foot.png
body/konqiteam/eyes.png
body/konqiteam/arm2.png
body/konqiteam/nose.png
body/konqiteam/horns.png
body/konqiteam/c1.png
body/konqiteam/helmet.png
body/konqiteam/foot-left.png
body/konqiteam/black.png
body/konqiteam/tail.png
body/konqiteam/body.png
body/konqiteam/wing.png
body/konqiteam/config.xml
body/konqiteam/c2.png
body/konqiteam/foot-right.png
body/konqiteam/dead.png
body/konqiteam/arm1.png
body/konqiteam/yoyo.png
body/wilberteam/c1.png
body/wilberteam/jetpack-belt.png
body/wilberteam/helmet.png
body/wilberteam/black.png
body/wilberteam/body.png
body/wilberteam/jetpack.png
body/wilberteam/config.xml
body/wilberteam/head.png
body/wilberteam/yoyo.svg
body/wilberteam/c2.png
body/wilberteam/dead.png
body/wilberteam/arm.png
body/wilberteam/jetpack-fire.png
body/wilberteam/yoyo.png
body/wilberteam/foot.png
body/tuxteam/eyes.png
body/tuxteam/c1.png
body/tuxteam/helmet.png
body/tuxteam/black.png
body/tuxteam/body.png
body/tuxteam/wing.png
body/tuxteam/config.xml
body/tuxteam/c2.png
body/tuxteam/dead.png
body/tuxteam/nozzle.png
body/tuxteam/yoyo.png
body/tuxteam/foot.png
body/spipteam/eyes.png
body/spipteam/c1.png
body/spipteam/jetpack-belt.png
body/spipteam/helmet.png
body/spipteam/black.png
body/spipteam/tail.png
body/spipteam/body.png
body/spipteam/jetpack.png
body/spipteam/config.xml
body/spipteam/head.png
body/spipteam/c2.png
body/spipteam/dead.png
body/spipteam/pupil.png
body/spipteam/arm.png
body/spipteam/jetpack-fire.png
body/spipteam/yoyo.png
body/spipteam/foot.png
body/firefoxteam/eyes.png
body/firefoxteam/arm2.png
body/firefoxteam/c1.png
body/firefoxteam/jetpack-belt.png
body/firefoxteam/helmet.png
body/firefoxteam/black.png
body/firefoxteam/tail.png
body/firefoxteam/body.png
body/firefoxteam/jetpack.png
body/firefoxteam/flag.png
body/firefoxteam/config.xml
body/firefoxteam/ear-right.png
body/firefoxteam/ear-left.png
body/firefoxteam/c2.png
body/firefoxteam/dead.png
body/firefoxteam/arm1.png
body/firefoxteam/pupil.png
body/firefoxteam/jetpack-fire.png
body/firefoxteam/yoyo.png
body/firefoxteam/foot.png
body/body.dtd
body/phpteam/c1.png
body/phpteam/jetpack-belt.png
body/phpteam/helmet.png
body/phpteam/foot-left.png
body/phpteam/black.png
body/phpteam/tail.png
body/phpteam/body.png
body/phpteam/jetpack.png
body/phpteam/config.xml
body/phpteam/head.png
body/phpteam/ear-right.png
body/phpteam/ear-left.png
body/phpteam/c2.png
body/phpteam/foot-right.png
body/phpteam/dead.png
body/phpteam/arm.png
body/phpteam/jetpack-fire.png
body/phpteam/yoyo.png
body/workraveteam/c1.png
body/workraveteam/jetpack-belt.png
body/workraveteam/helmet.png
body/workraveteam/black.png
body/workraveteam/body.png
body/workraveteam/jetpack.png
body/workraveteam/config.xml
body/workraveteam/head.png
body/workraveteam/c2.png
body/workraveteam/dead.png
body/workraveteam/arm.png
body/workraveteam/jetpack-fire.png
body/workraveteam/yoyo.png
body/workraveteam/foot.png
body/nupikteam/spines2.png
body/nupikteam/c1.png
body/nupikteam/jetpack-heli.png
body/nupikteam/helmet.png
body/nupikteam/black.png
body/nupikteam/body.png
body/nupikteam/spines1.png
body/nupikteam/jetpack.png
body/nupikteam/config.xml
body/nupikteam/head.png
body/nupikteam/c2.png
body/nupikteam/dead.png
body/nupikteam/arm.png
body/nupikteam/fixedarm.png
body/nupikteam/yoyo.png
body/nupikteam/foot.png
body/oooteam/eyes.png
body/oooteam/c1.png
body/oooteam/helmet.png
body/oooteam/black.png
body/oooteam/body.png
body/oooteam/wingright.png
body/oooteam/config.xml
body/oooteam/c2.png
body/oooteam/wingleft.png
body/oooteam/dead.png
body/oooteam/nozzle.png
body/oooteam/yoyo.png
body/oooteam/foot.png
body/thunderbirdteam/eyes.png
body/thunderbirdteam/c1.png
body/thunderbirdteam/helmet.png
body/thunderbirdteam/black.png
body/thunderbirdteam/body.png
body/thunderbirdteam/wingright.png
body/thunderbirdteam/config.xml
body/thunderbirdteam/c2.png
body/thunderbirdteam/wingleft.png
body/thunderbirdteam/dead.png
body/thunderbirdteam/nozzle.png
body/thunderbirdteam/hair.png
body/thunderbirdteam/yoyo.png
body/thunderbirdteam/foot.png
body/gnuteam/c1.png
body/gnuteam/jetpack-belt.png
body/gnuteam/helmet.png
body/gnuteam/black.png
body/gnuteam/tail.png
body/gnuteam/body.png
body/gnuteam/jetpack.png
body/gnuteam/config.xml
body/gnuteam/head.png
body/gnuteam/c2.png
body/gnuteam/dead.png
body/gnuteam/arm.png
body/gnuteam/jetpack-fire.png
body/gnuteam/yoyo.png
body/gnuteam/foot.png
authors.xml
authors.dtd
game_mode/classic.xml~
game_mode/game_mode.dtd
game_mode/classic.xml
game_mode/objects.xml~
game_mode/objects.dtd
game_mode/objects.xml
wormux_128x128.xpm
graphism.xml~
wormux_256x256.png
sound/share/explosion.ogg
sound/share/laughing.ogg
sound/share/end_turn.ogg
sound/share/victory.ogg
sound/share/step.ogg
sound/share/frog_music.ogg
sound/share/profile.xml
sound/share/menu/ok.ogg
sound/share/menu/cancel.ogg
sound/share/menu/clic.ogg
sound/flying/profile.xml
sound/flying/flying.ogg
sound/francais/fire_01.ogg
sound/francais/crazy.ogg
sound/francais/profile.xml
sound/francais/fire_02.ogg
sound/default/uuh_08.ogg
sound/default/death_01.ogg
sound/default/out_01.ogg
sound/default/crazy_04.ogg
sound/default/hop_01.ogg
sound/default/uuh_07.ogg
sound/default/uuh_06.ogg
sound/default/uuh_01.ogg
sound/default/step_01.ogg
sound/default/uuh_03.ogg
sound/default/fire_01.ogg
sound/default/sink.ogg
sound/default/crazy_03.ogg
sound/default/crazy_02.ogg
sound/default/uuh_02.ogg
sound/default/crazy_01.ogg
sound/default/cuss_01.ogg
sound/default/skip_turn.ogg
sound/default/cuss_02.ogg
sound/default/suicide_01.ogg
sound/default/hehe.ogg
sound/default/superjump_01.ogg
sound/default/step_02.ogg
sound/default/cuss_03.ogg
sound/default/profile.xml
sound/default/death_02.ogg
sound/default/fire_02.ogg
sound/default/crazy_05.ogg
sound/default/uuh_04.ogg
sound/default/uuh_05.ogg
sound/default/cuss_04.ogg
font/DejaVuSans.ttf
graphism.dtd
weapon/anvil/anvil_launcher.png
weapon/anvil/anvil.png
weapon/anvil/anvil_ico.png
weapon/syringe/syringe.png
weapon/syringe/syringe_ico.png
weapon/bazooka/bazooka_auto_ico.png
weapon/bazooka/bazooka_ico.png
weapon/bazooka/baz_cible.png
weapon/bazooka/bazooka.png
weapon/bazooka/missile.png
weapon/lowgrav/lowgrav_ico.png
weapon/teleportation/teleportation_ico.png
weapon/teleportation/teleportation.png
weapon/mine/mine_impact.png
weapon/mine/mine_anim.png
weapon/mine/mine_ico.png
weapon/mine/mine.png
weapon/skip_turn/skipturn_ico.png
weapon/skip_turn/skipturn.png
weapon/bounce_ball/bounce_ball.png
weapon/bounce_ball/bounce_ball_ico.png
weapon/disco_grenade/disco_grenade.png
weapon/disco_grenade/disco_grenade_ico.png
weapon/cluster_bomb/clusterbomb.png
weapon/cluster_bomb/cluster.png
weapon/cluster_bomb/clusterbomb_ico.png
weapon/polecat/polecat.png
weapon/polecat/polecat_ico.png
weapon/polecat/polecatlauncher.png
weapon/polecat/polecat_fart.png
weapon/dynamite/dynamite_ani.png
weapon/dynamite/dynamite_ico.png
weapon/dynamite/dynamite.png
weapon/jet_pack/jet_pack_ico.png
weapon/shotgun/shotgun_ico.png
weapon/shotgun/buckshot.png
weapon/shotgun/shotgun.png
weapon/ninja_rope/ninjanode.png
weapon/ninja_rope/ninjahook.png
weapon/ninja_rope/ninjarope_ico.png
weapon/ninja_rope/ninjarope.png
weapon/blowtorch/fire.png
weapon/blowtorch/blowtorch.png
weapon/blowtorch/blowtorch_ico.png
weapon/gnu/gnu.png
weapon/gnu/gnulauncher.png
weapon/gnu/gnu_ico.png
weapon/sound/pistolet.ogg
weapon/sound/dynamite_exp.ogg
weapon/sound/baseball.ogg
weapon/sound/shotgun.ogg
weapon/sound/ricoche2.ogg
weapon/sound/ricoche1.ogg
weapon/sound/teleport_start.ogg
weapon/sound/grenade_bounce.ogg
weapon/sound/alleluia.ogg
weapon/sound/commit_suicide.ogg
weapon/sound/gun.ogg
weapon/sound/teleport_land.ogg
weapon/sound/riot_bomb_exp.ogg
weapon/sound/dynamite.ogg
weapon/sound/m16.ogg
weapon/sound/load.ogg
weapon/sound/mine_beep.ogg
weapon/sound/ricoche3.ogg
weapon/sound/airhammer.ogg
weapon/sound/dynamite_fuze.ogg
weapon/sound/holly_grenade_bounce.ogg
weapon/sound/jetpack.ogg
weapon/snipe_rifle/snipe_rifle_laser.png
weapon/snipe_rifle/snipe_rifle.png
weapon/snipe_rifle/snipe_rifle_ico.png
weapon/parachute/parachute.png
weapon/parachute/parachute_ico.png
weapon/construct/construct_icon.png
weapon/construct/construct_icon_mini.png
weapon/construct/construct_spr.png
weapon/airhammer/airhammer_impact.png
weapon/airhammer/airhammer.png
weapon/airhammer/airhammer_ico.png
weapon/supertux/superman.png
weapon/supertux/supertux.png
weapon/supertux/supertux_ico.png
weapon/baseball/baseball_hit.png
weapon/baseball/baseball_ico.png
weapon/baseball/baseball.png
weapon/suicide/suicide.png
weapon/suicide/suicide_ico.png
weapon/riot_bomb/riot_ico.png
weapon/riot_bomb/missile.png
weapon/air_attack/air_attack.png
weapon/air_attack/air_attack_plane.png
weapon/air_attack/obus.png
weapon/air_attack/air_attack_ico.png
weapon/m16/m16.png
weapon/m16/m16_ico.png
weapon/gun/gun_fire.png
weapon/gun/gun.png
weapon/gun/gun_ico.png
weapon/gun/gun_bullet.png
weapon/grenade/grenade_ico.png
weapon/grenade/grenade.png
team/team.dtd
team/snortteam/flag.png
team/snortteam/team.xml
team/beastieteam/flag.png
team/beastieteam/team.xml
team/konqiteam/flag.png
team/konqiteam/team.xml
team/wilberteam/flag.png
team/wilberteam/team.xml
team/tuxteam/flag.png
team/tuxteam/team.xml
team/spipteam/flag.png
team/spipteam/team.xml
team/spipteam/flag.svg
team/firefoxteam/flag.png
team/firefoxteam/team.xml
team/phpteam/flag.png
team/phpteam/team.xml
team/workraveteam/flag.png
team/workraveteam/team.xml
team/nupikteam/flag.png
team/nupikteam/team.xml
team/oooteam/flag.png
team/oooteam/team.xml
team/thunderbirdteam/flag.png
team/thunderbirdteam/team.xml
team/gnuteam/flag.png
team/gnuteam/team.xml
wormux_32x32.xpm
menu/img/display_wind_particles.png
menu/img/plus.png
menu/img/scroll_on_border.png
menu/img/audio_label.png
menu/img/display_name.png
menu/img/skin01.png
menu/img/sound_effects_enable.png
menu/img/arrow-left.png
menu/img/music_enable.png
menu/img/minus.png
menu/img/skin02.png
menu/img/teams_label.png
menu/img/loading.png
menu/img/title.png
menu/img/check.png
menu/img/ico_sounds.png
menu/img/big_left.png
menu/img/video_label.png
menu/img/timing_end_turn.png
menu/img/ico_weapons.png
menu/img/cancel.png
menu/img/arrow-right.png
menu/img/background_play.png
menu/img/validate.png
menu/img/down.png
menu/img/send_txt.png
menu/img/display_energy.png
menu/img/background_network.png
menu/img/mode_label.png
menu/img/ico_skins.png
menu/img/map_label.png
menu/img/big_right.png
menu/img/timing_turn.png
menu/img/fullscreen.png
menu/img/background.png
menu/img/background_credits.png
menu/img/up.png
menu/img/button.png
menu/img/background_options.png
menu/img/ico_maps.png
wormux.svg
)
